theme: jekyll-theme-midnight

title: Personal Website
show_downloads: true
google_analytics: [UA-104676221-1]
username: Igor Sim√µes
github_username: igor-simoes
gmail: isol2@cin.ufpe.br
linkedin: igorsimoesol
personal: iigor.simoes
last_updated: Tue May 23 2018